#!/bin/bash
# number of threads:
thing() {
    echo -e "ArrLen\tTries\tSSE Run\tnon-SSE run\tMultithread Run\tThreads"
    for al in 1024 8192 131072 1048576 2097152 4194304 8388608
    do
        
        for  nt  in 10 50 100 200 300
        do
            for th in 2 4 8 16
            do
                echo -ne "$al\t$nt"
                g++   -DNUM_TRIALS=$nt   -DARRAY_LENGTH=$al -DNUMT=$th   prog.cpp  -o prog  -lm  -fopenmp
                ./prog
            done
        done
    done
}

thing > perfomance$$.csv



