#!/bin/bash
# number of threads:
thing() {
    for  nt  in  10 50 100 200 300
    do
        for al in 1000 10000 100000 1000000 2000000 4000000 8000000
        do
            g++   -DNUM_TRIALS=$nt   -DARRAY_LENGTH=$al   prog.cpp  -o prog  -lm  -fopenmp
            ./prog
        done
        echo
    done
}

thing > perfomance$$.csv



