#!/bin/bash
# number of threads:
thing() {
    # number of subdivisions:
    flag=0
    if [ $# == 1 ] && [ $1 == 'monthsOnly' ]
    then
        flag=1
    fi
    g++ -DMONTHSONLY prog.cpp  -o prog  -lm   -fopenmp
    ./prog
    echo
}

thing > output$$.csv
thing monthsOnly > monthsOutput$$.csv



